### ISSUE TITLE
Slow execution time of method

### ISSUE THREAD

**Issue by eddyod** [eddyod/pipeline_utility#10]
@qobilidop 
Bili, check this method 'scaled' in:
https://github.com/eddyod/pipeline_utility/blob/master/utilities/utilities_mask.py at line 270. It works fine but is really slow on full resolution images. Is there anything we can do to make it faster? This method works nicely to scale all the values in the image, like the histogram equalization method.

**Comment by qobilidop** [comment]
A potential speedup is to use `np.quantile`. I did a simple benchmark:
![image](https://user-images.githubusercontent.com/5176695/103241631-ab73ef80-4908-11eb-8c16-3f4de1ffdaee.png)

**Comment by eddyod** [comment]
I tested on a 125MB image and the original code:
vals = np.array(sorted(img[mask > 10]))  
took 148 seconds. Then I simply got rid of sorted and used numpy's sort:
vals = np.sort(img[mask > 10])
That took 12 seconds, which I was very happy with, but then I just used quantile:
_max = np.quantile(img[img > 10], 1 - epsilon)
and that took 1.9 seconds, so that is even better.
