### ISSUE TITLE
Improving the performance of create_alignment.py

### ISSUE THREAD

**Issue by eddyod** [eddyod/pipeline_utility#13]
We use Imagemagick's convert tool to rotate and translate the images. This works well but it is really slow on the big images. Here is one of the commands:

"convert /net/birdstore/Active_Atlas_Data/data_root/pipeline_data/DK41/preps/CH1/full_cleaned/250.tif -define white-point=0x0 +repage -virtual-pixel background -background black +distort AffineProjection 0.995548287659264,-0.09425288822474763,0.09425288822474764,0.9955482876592641,-1827.5865180979245,4902.472809344063 -crop 57600x32000+0.0+0.0! -flatten -compress lzw /net/birdstore/Active_Atlas_Data/data_root/pipeline_data/DK41/preps/CH1/full_aligned/250.tif"

The important part of the above command is the "+distort AffineProjection 0.995548287659264,-0.09425288822474763,0.09425288822474764,0.9955482876592641,-1827.5865180979245,4902.472809344063 -crop 57600x32000+0.0+0.0!"

That is where the rotation and translation are. Those numbers come from the elastix data from a  previous step. Can you perhaps do this in python? Right now we use subprocess.Popen to call convert. I don't know if it would be any faster but we should try.

This command is called in this program:
https://github.com/eddyod/pipeline_utility/blob/master/create_alignment.py

Look around line 227.

**Comment by qobilidop** [comment]
Sure, I'll take a look.

**Comment by qobilidop** [comment]
I tried implementing affine transform and crop with [pillow](https://pillow.readthedocs.io/). Here is an example:
```python
from PIL import Image

Image.MAX_IMAGE_PIXELS = None

input_file = '/net/birdstore/Active_Atlas_Data/data_root/pipeline_data/DK41/preps/CH1/thumbnail_cleaned/250.tif'
output_file = 'test_250.tif'

im1 = Image.open(input_file)

# affine transform
sx,rx,ry,sy,tx,ty = 0.995548287659264,-0.09425288822474763,0.09425288822474764,0.9955482876592641,0,0
im2 = im1.transform(im1.size, Image.AFFINE, data=[sx,rx,tx,ry,sy,ty], resample=Image.NEAREST)

# crop
w, h = im2.size
left, upper, right, lower = 200, 0, w, h - 300
im2 = im2.crop((left, upper, right, lower))

im2.save(output_file)
```

I couldn't find the `full_cleaned` directory, so I used `thumbnail_cleaned` instead. Following are `im1` and `im2` respectively:
![image](https://user-images.githubusercontent.com/5176695/110680008-f756d680-818c-11eb-8d1b-a84d3db122e9.png)
![image](https://user-images.githubusercontent.com/5176695/110680050-00e03e80-818d-11eb-9a2e-5ff0992bffdc.png)

**Comment by qobilidop** [comment]
@eddyod
Here's the performance comparison result:

```bash
$ time convert /net/birdstore/Active_Atlas_Data/data_root/pipeline_data/DK52/preps/CH1/full_cleaned/250.tif -define white-point=0x0 +repage -virtual-pixel background -background black +distort AffineProjection 0.995548287659264,-0.09425288822474763,0.09425288822474764,0.9955482876592641,-1827.5865180979245,4902.472809344063 -crop 57600x32000+0.0+0.0! -flatten -compress lzw test_250_convert.tif

real    4m27.390s
user    30m39.692s
sys     1m19.981s
```

```bash
$ time python test.py

real    1m37.887s
user    1m31.012s
sys     0m6.829s
```

`test.py`:
```python
from PIL import Image

Image.MAX_IMAGE_PIXELS = None

input_file = '/net/birdstore/Active_Atlas_Data/data_root/pipeline_data/DK52/preps/CH1/full_cleaned/250.tif'
output_file = 'test_250_pillow.tif'

im1 = Image.open(input_file)

# affine transform
sx,rx,ry,sy,tx,ty = 0.995548287659264,-0.09425288822474763,0.09425288822474764,0.9955482876592641,-1827.5865180979245,4902.472809344063
im2 = im1.transform(im1.size, Image.AFFINE, data=[sx,rx,tx,ry,sy,ty], resample=Image.NEAREST)

# crop
# w, h = im2.size
left, upper, right, lower = 0, 0, 57600, 32000
im3 = im2.crop((left, upper, right, lower))

im3.save(output_file)
```

It seems the Python script is faster, but it might be because the convert command is doing more than just affine transform and crop.

**Comment by eddyod** [comment]
@qobilidop can you look at the:
https://github.com/eddyod/pipeline_utility/blob/master/create_alignment.py 
I implemented the PIL code (line 236) but the resulting images were not aligned at all.
Try running but change the output directory to someplace you can write to.

**Comment by eddyod** [comment]
I removed the crop and fixed the parameters. It works nicely and fast.
