### ISSUE TITLE
Section to section alignment with ITK

### ISSUE THREAD

**Issue by eddyod** [eddyod/pipeline_utility#9]
Bili,
Take a look at this notebook,
pipeline_utility/utilities/notebooks/itk_process_dir.ipynb

This is a redone version of the Yuncongs elastix script. I changed it to use ITK instead of elastix. It basically runs through all the images of a stack, gets the rotation matrix for each pair of images and sends that data to Imagemagick's convert command.
I'm not getting great results though. Can you take a look?

**Comment by eddyod** [comment]
I updated and cleaned the code and it is much more readable.

**Comment by eddyod** [comment]
This ITK registration process is now working well on a full stack of images,
pipeline_utility/utilities/notebooks/basic_itk.ipynb
This notebook is useful for fine tuning,
utilities/notebooks/basic_itk.ipynb

**Comment by eddyod** [comment]
I added an iterative process that is working well, but I'm not sure about some things. Bili, take a look at:
https://github.com/eddyod/pipeline_utility/blob/master/registration/create_registration.py especially line 55.

**Comment by eddyod** [comment]
@qobilidop 
Bili, I updated the script:
https://github.com/eddyod/pipeline_utility/blob/master/registration/create_registration.py
Please look at line 77 if that makes sense. I'm using this script to get the best rotation matrix possible. It loops over all the input files and keeps updating the rotation matrix.

**Comment by qobilidop** [comment]
> @qobilidop
> Bili, I updated the script:
> https://github.com/eddyod/pipeline_utility/blob/master/registration/create_registration.py
> Please look at line 77 if that makes sense. I'm using this script to get the best rotation matrix possible. It loops over all the input files and keeps updating the rotation matrix.

I think it's correct.
